### ISSUE TITLE
ImportError: cannot import name logs

### ISSUE THREAD

**Issue by tivrobo** [NDrive/graylog-archiver#1]
Hi!

First, I want to thank you for this project!

I have Ubuntu 14 LTS with Graylog already installed.
Today I was tried to setup graylog-archiver with simple steps:

```
apt-get update
apt-get install python-pip
pip install graylog-archiver
```

Then I have created directory for backups, graylog-archiver config file, make changes to elasticsearch.yml, restart it.

But unfortunately, when I try to run it I see Python errors:

```
root@graylog:~# uname -a
Linux graylog 4.4.0-31-generic #50~14.04.1-Ubuntu SMP Wed Jul 13 01:07:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

```
root@kv-graylog:~# python --version
Python 2.7.6

```

```
root@graylog:~# graylog-archiver
Traceback (most recent call last):
  File "/usr/local/bin/graylog-archiver", line 9, in <module>
    load_entry_point('graylog-archiver==0.1.3', 'console_scripts', 'graylog-archiver')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/graylog_archiver/cli.py", line 3, in <module>
    from graylog_archiver.graylog_archiver import GraylogArchiver
  File "/usr/local/lib/python2.7/dist-packages/graylog_archiver/graylog_archiver.py", line 3, in <module>
    from graylog_archiver import logs
ImportError: cannot import name logs
```

I have tried to google and find some:
https://stackoverflow.com/questions/14413896/importerror-cannot-import-name-log
but renaming logs.py to graylog_logs.py (and all references in code) didn't help...

Maybe you know what is this and how to fix it?

**Comment by andrefreitas** [comment]
Hi,
I believe this is related with the fact that you are using Python 2 and not 3. (I must add to the Readme).

Please use Python 3 and tell me if it works.

**Comment by tivrobo** [comment]
Hi,

Get it to work by removing `graylog_archiver` prefix from import statements:

For example file: graylog_archiver.py

Before:
```
import shutil
from graylog_archiver import logs
from graylog_archiver.graylog_elasticsearch import GraylogElasticsearch
from graylog_archiver.utils import compress_directory
```

After:
```
import shutil
import logs
from graylog_elasticsearch import GraylogElasticsearch
from utils import compress_directory
```

I change all files like that and now all works as expected!

Note: this is on Python 2

**Comment by tivrobo** [comment]
I will try to test your code on machine with Python 3, and let you know the results.

**Comment by andrefreitas** [comment]
Sure, relative imports in Python 2 [1] are different from Python 3 [2].

Links:
1. https://docs.python.org/2.5/whatsnew/pep-328.html
2. https://www.python.org/dev/peps/pep-0328/

**Comment by tivrobo** [comment]
In Python 3 environment all works out-of-box!
Thank you!

**Comment by andrefreitas** [comment]
Sure, thanks for letting me know!
